name: Run Doctests

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  doctests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2
        with:
          cpp-version: "17"
          compiler: "gcc"

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install doctest
        run: |
          wget -O doctest.h https://github.com/onqtam/doctest/raw/master/doctest/doctest.h
          mkdir -p include
          mv doctest.h include/

      - name: Build and run tests
        run: |
          cmake -DCOUNTLY_BUILD_TESTS=1 -B build .
          cd build
          make ./countly-tests
          ./countly-tests
