name: Run Doctests

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  doctests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install doctest
        run: |
          wget -O doctest.h https://github.com/onqtam/doctest/raw/master/doctest/doctest.h
          mkdir -p include
          mv doctest.h include/

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libcurl4-openssl-dev

      - name: Build and run tests
        run: |
          cmake -DCOUNTLY_BUILD_TESTS=1 -B build .
          cd build
          make ./countly-tests
          ./countly-tests
        continue-on-error: true
